# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: lsgames-forum-backend
  labels:
    app: lsgames-forum-backend
  namespace: smkz-for-work
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lsgames-forum-backend
  template:
    metadata:
      labels:
        app: lsgames-forum-backend
    spec:
      containers:
        - name: lsgames-forum-backend
          image: $secrets.REGISTRY_URL/lsgames-forum-backend:latest
          resources:
            requests:
              memory: 512Mi
              cpu: 250m
            limits:
              memory: 512Mi
              cpu: 250m
          ports:
            - containerPort: 80
              protocol: TCP
          env:
            - name: DB_HOST
              valueFrom:
                secretKeyRef:
                  name: lsgames-forum-secrets
                  key: database.host
            - name: DB_PORT
              valueFrom:
                configMapKeyRef:
                  name: lsgames-forum-configs
                  key: database.port
            - name: DB_DATABASE
              valueFrom:
                configMapKeyRef:
                  name: lsgames-forum-configs
                  key: database.name
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: lsgames-forum-secrets
                  key: database.username
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: lsgames-forum-secrets
                  key: database.password
            - name: REQUEST_CLIENT_VERIFY_SSL
              valueFrom:
                configMapKeyRef:
                  name: lsgames-forum-configs
                  key: request.verifyssl
            - name: SINGLE_SIGN_ON_BACKEND
              valueFrom:
                configMapKeyRef:
                  name: lsgames-forum-configs
                  key: services.singlesignon

---
# service.yaml
apiVersion: v1
kind: Service
metadata:
  name: lsgames-forum-backend
  namespace: smkz-for-work
spec:
  type: ClusterIP
  selector:
    app: lsgames-forum-backend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
